In [50]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from imblearn.combine import SMOTEENN

In [20]:
df=pd.read_csv('tel_churn.csv')

In [21]:
df.head()

,Unnamed: 0,SeniorCitizen,MonthlyCharges,TotalCharges,Churn,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,...,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_group_1 - 12,tenure_group_13 - 24,tenure_group_25 - 36,tenure_group_37 - 48,tenure_group_49 - 60,tenure_group_61 - 72
0,0,0,29,29,0,1,0,0,1,1,...,0,0,1,0,1,0,0,0,0,0
1,1,0,56,1889,0,0,1,1,0,1,...,0,0,0,1,0,0,1,0,0,0
2,2,0,53,108,1,0,1,1,0,1,...,0,0,0,1,1,0,0,0,0,0
3,3,0,42,1840,0,0,1,1,0,1,...,1,0,0,0,0,0,0,1,0,0
4,4,0,70,151,1,1,0,1,0,1,...,0,0,1,0,1,0,0,0,0,0

In [22]:
df=df.drop('Unnamed: 0',axis=1)

In [24]:
X=df.drop('Churn',axis=1)
X

,SeniorCitizen,MonthlyCharges,TotalCharges,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,PhoneService_No,...,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_group_1 - 12,tenure_group_13 - 24,tenure_group_25 - 36,tenure_group_37 - 48,tenure_group_49 - 60,tenure_group_61 - 72
0,0,29,29,1,0,0,1,1,0,1,...,0,0,1,0,1,0,0,0,0,0
1,0,56,1889,0,1,1,0,1,0,0,...,0,0,0,1,0,0,1,0,0,0
2,0,53,108,0,1,1,0,1,0,0,...,0,0,0,1,1,0,0,0,0,0
3,0,42,1840,0,1,1,0,1,0,1,...,1,0,0,0,0,0,0,1,0,0
4,0,70,151,1,0,1,0,1,0,0,...,0,0,1,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,0,84,1990,0,1,0,1,0,1,0,...,0,0,0,1,0,1,0,0,0,0
7028,0,103,7362,1,0,0,1,0,1,0,...,0,1,0,0,0,0,0,0,0,1
7029,0,29,346,1,0,0,1,0,1,1,...,0,0,1,0,1,0,0,0,0,0
7030,1,74,306,0,1,0,1,1,0,0,...,0,0,0,1,1,0,0,0,0,0
7031,0,105,6844,0,1,1,0,1,0,0,...,1,0,0,0,0,0,0,0,0,1

In [25]:
y=df['Churn']
y

0       0
1       0
2       1
3       0
4       1
       ..
7027    0
7028    0
7029    0
7030    1
7031    0
Name: Churn, Length: 7032, dtype: int64

#### Train Test Split

In [33]:
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2)

#### Decision Tree Classifier

In [34]:
from sklearn.tree import DecisionTreeClassifier

In [37]:
model_dt= DecisionTreeClassifier(criterion='gini', random_state=100,min_samples_leaf = 8)

In [38]:
model_dt.fit(X_train,y_train)

DecisionTreeClassifier(min_samples_leaf=8, random_state=100)

In [42]:
y_pred_dt0= model_dt.predict(X_test)

In [43]:
accuracy_score(y_test,y_pred_dt0)

0.7647476901208244

In [46]:
print(classification_report(y_test,y_pred_dt0, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.84      0.85      0.84      1055
           1       0.53      0.50      0.52       352

    accuracy                           0.76      1407
   macro avg       0.68      0.68      0.68      1407
weighted avg       0.76      0.76      0.76      1407

In [52]:
sm=SMOTEENN()
x_resampled,y_resampled=sm.fit_resample(X,y)

In [53]:
X_train_sm,X_test_sm,y_train_sm,y_test_sm=train_test_split(x_resampled,y_resampled,test_size=0.2)

In [63]:
model_dt_sm= DecisionTreeClassifier(criterion='gini', random_state=100,max_depth=6,min_samples_leaf = 8)

In [64]:
model_dt_sm.fit(X_train_sm,y_train_sm)

DecisionTreeClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [65]:
y_pred_dt_sm= model_dt.predict(X_test_sm)

In [66]:
print(classification_report(y_test_sm,y_pred_dt_sm, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.72      0.97      0.83       549
           1       0.97      0.67      0.79       618

    accuracy                           0.81      1167
   macro avg       0.85      0.82      0.81      1167
weighted avg       0.85      0.81      0.81      1167

In [67]:
accuracy_score(y_test_sm,y_pred_dt_sm)

0.8140531276778064

#### Random Forest Classifier

In [68]:
from sklearn.ensemble import RandomForestClassifier

In [69]:
model_rf = RandomForestClassifier(n_estimators =100, criterion='gini', random_state=100,max_depth=6,min_samples_leaf=8)

In [70]:
model_rf.fit(X_train_sm,y_train_sm)

RandomForestClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [71]:
y_pred_rf= model_rf.predict(X_test_sm)

In [72]:
print(classification_report(y_test_sm,y_pred_rf, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.96      0.89      0.92       549
           1       0.90      0.97      0.94       618

    accuracy                           0.93      1167
   macro avg       0.93      0.93      0.93      1167
weighted avg       0.93      0.93      0.93      1167

In [73]:
accuracy_score(y_test_sm,y_pred_rf)

0.9297343616109683

#### Logistic Regeression

In [107]:
from sklearn.linear_model import LogisticRegression

In [125]:
model_lr = LogisticRegression(max_iter=500)

In [126]:
model_lr.fit(X_train_sm,y_train_sm)

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 500 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=500).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=500)

In [127]:
y_pred_lr= model_lr.predict(X_test_sm)

In [128]:
print(classification_report(y_test_sm,y_pred_lr, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.95      0.94      0.94       549
           1       0.95      0.96      0.95       618

    accuracy                           0.95      1167
   macro avg       0.95      0.95      0.95      1167
weighted avg       0.95      0.95      0.95      1167

In [129]:
accuracy_score(y_test_sm,y_pred_lr)

0.9477292202227935

#### AdaBoost

In [113]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier

In [114]:
base_model_ab = DecisionTreeClassifier(max_depth=1)

In [115]:
model_ab= AdaBoostClassifier( estimator= base_model_ab, n_estimators = 50, learning_rate=1,random_state=42)

In [116]:
model_ab.fit(X_train_sm,y_train_sm)

AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=1),
                   learning_rate=1, random_state=42)

In [117]:
y_pred_ab= model_ab.predict(X_test_sm)

In [118]:
print(classification_report(y_test_sm,y_pred_ab, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.95      0.90      0.92       549
           1       0.92      0.95      0.94       618

    accuracy                           0.93      1167
   macro avg       0.93      0.93      0.93      1167
weighted avg       0.93      0.93      0.93      1167

In [119]:
accuracy_score(y_test_sm,y_pred_ab)

0.9297343616109683

### Conclusion
- accuracy score for Decision Tree classifier is 81.4.
- accuracy score for Random Forest classifier is 92.9.
- accuracy score for Logistic Regressor Tree  is 94.7.
- accuracy score for Adaboost Classifier is 92.9.

##### Hence the model trained with logistic regression is giving the best result